create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  project_type text,
  budget text,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

revoke all on public.contact_submissions from anon, authenticated;
